# -*- coding: utf-8 -*-
"""Career AI Abdullah Asim

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HllzuqCRSCqZLlMzazJnU7FQ2qKGCQzQ

# 🚀 CrewAI Hands-On: Build an AI Career Coach Agent

Welcome to this hands-on activity! 🎓

Today, we'll build an **AI Career Coach Agent** using [CrewAI](https://github.com/joaomdmoura/crewAI). This agent will suggest exciting career paths for teens based on their interests.

By the end of this notebook, you'll:
- Understand what an AI agent is
- Create a one-agent CrewAI app
- See how AI can help with real-life questions

## 📦 Step 1: Install Required Libraries
"""

!pip install crewai openai langchain_openai -q

"""## 🧠 Step 2: Import Python Libraries"""

from crewai import Agent, Task, Crew
from langchain_openai import ChatOpenAI

"""## 🔐 Step 3: Add Your OpenAI API Key"""

import os
os.environ['OPENAI_API_KEY'] = "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"

"""## 🤖 Step 4: Initialize the Language Model"""

from langchain_openai import ChatOpenAI
llm = ChatOpenAI(model_name="gpt-4o-mini")

"""## 🧑‍🏫 Step 5: Define the AI Career Coach Agent"""

career_coach = Agent(
    role="career coach for teens",
    goal="help teenagers explore exciting and personalised career path based on their interests",
    backstory="you are a cool , inspiring career coach who know all the modern and future ready career options. your mission is to guide team to dream big and take the first step towards their goals",
    llm = llm
)
#motivation coach
motivation_coach = Agent(
    role="motivation coach ",
    goal="inspire the student with encouragement and a firstaction step",
    backstory="you're a high-energy motivator who pushes students to chase their dreams",
    llm = llm
)
#resource finder
resource_finder= Agent(
    role="learn resource expert",
    goal="suggest 1-2 beginner-friendly resources to start learning about the career",
    backstory="you are a research genius who find the best youtube video, blog posts,or course",
    llm = llm

)
#supervisor agenr
supervisor =Agent(
    role="career planning supervisor",
    goal="REview the work of all the agents and compile it into a complete final message for the student",
    backstory="You are the wise team leader who combines the advice into a single, clear, helpful report",
    llm = llm
)

"""## 📝 Step 6: Create a Task for the Agent
Let’s ask the agent to suggest a career path based on a student's interest.
"""

interest=input("What are you interested in: ")
task1=Task(
    description=f"""suggest a modern exciting career path for a teen who is interested in {interest}. Explain why this career fits and give some tips to start exploring it today""",
    expected_output="a career suggestion, a reason it fits, and one actionable tip for getting started.",
    agent=career_coach

)


#Task 2 -Motivation Message
task2= Task(
    description="Give a motivational quote or message and suggest a first small action step",
    expected_output="1 quote/message + 1 action step",
    agent=motivation_coach,
    depends_on=[task1]
)



#Task 3 - Learning Resources
task3= Task(
    description="Find 1-2 beginner friendly resources (Youtube, blogs, courses) for the career suggested",
    expected_output="List of 1-2 links or descriptions",
    agent=resource_finder,
    depends_on=[task1]
)


#Task4 - Supervisor final summary
task4= Task(
    description="Take the output from all tasks and write the final message for the student with career name",
    expected_output="Final 5-6 line message with all outputs combined",
    agent=supervisor,
    depends_on=[task1, task2, task3]
)

"""## 🚀 Step 7: Run the Agent and Get Career Advice"""

crew = Crew(
    agents=[career_coach,motivation_coach,resource_finder,supervisor],
    tasks=[task1,task2,task3,task4]
)

result = crew.kickoff()
print("🎯 Final AI Career Plan:\n")
print(result)